src/Entity/Uname.php
<?php

namespace Aequation\WireBundle\Entity;

use Aequation\WireBundle\Attribute\ClassCustomService;
use Aequation\WireBundle\Entity\IdGenerator\UnameIdGenerator;
use Aequation\WireBundle\Entity\interface\TraitUnamedInterface;
use Aequation\WireBundle\Entity\interface\UnameInterface;
use Aequation\WireBundle\Entity\interface\WireEntityInterface;
use Aequation\WireBundle\Repository\UnameRepository;
use Aequation\WireBundle\Service\interface\UnameServiceInterface;
use Aequation\WireBundle\Tools\Encoders;
use Doctrine\DBAL\Types\Types;
// Symfony
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Uid\UuidV7 as Uuid;
// PHP
use Exception;

#[ORM\Entity(repositoryClass: UnameRepository::class)]
#[ORM\Table(name: '`u_name`')]
// #[UniqueEntity(fields: ['euid'], message: 'Cet EUID {{ value }} est déjà utilisé !', groups: ['persist','update'])]
#[UniqueEntity('entityEuid', message: 'Cette entité (euid: {{ value }}) est déjà utilisé !', groups: ['persist','update'])]
#[ClassCustomService(UnameServiceInterface::class)]
class Uname extends BaseMappSuperClassEntity implements UnameInterface
{

    public const ICON = [
        'ux' => 'tabler:fingerprint',
        'fa' => 'fa-fingerprint'
    ];
    public const RESERVED_UNAMES = ['uname', 'id', 'euid', 'entityEuid', 'entity', 'entityClassname', 'entityShortname', 'entityEuid', 'entityId', 'entityUname', 'entityUnameId', 'entityUnameEuid'];

    #[ORM\Id]
    #[ORM\Column(updatable: false, type: Types::STRING, unique: true)]
    #[Assert\Length(min: 3, minMessage: 'Uname doit contenir au moins {{ min }} lettres', groups: ['persist','update'])]
    #[Assert\Regex(pattern: Encoders::UNAME_SCHEMA, groups: ['persist','update'])]
    protected ?string $id = null;

    #[ORM\Column(updatable: false, unique: true)]
    #[Assert\NotNull(groups: ['persist','update'])]
    #[Assert\Regex(pattern: Encoders::EUID_SCHEMA, groups: ['persist','update'])]
    protected string $entityEuid;

    public readonly WireEntityInterface $entity;

    /**
     * get self as string
     * 
     * @return string
     */
    public function __toString(): string
    {
        return $this->getUname();
    }

    #[Assert\IsTrue(groups: ['persist','update'])]
    public function isValid(): bool
    {
        return Encoders::isUnameFormatValid($this->id);
    }

    /**
     * attribute entity
     * 
     * @param TraitUnamedInterface $entity
     * @param string|null $uname
     * @return static
     */
    public function attributeEntity(
        TraitUnamedInterface $entity,
        ?string $uname = null
    ): static {
        $this->entity ??= $entity;
        if ($this->entity !== $entity) {
            throw new Exception(vsprintf("Error %s line %d:%s- Can not set another entity!", [__METHOD__, __LINE__, PHP_EOL]));
        }
        if (!empty($uname) || empty($this->id)) {
            if (empty($uname)) $uname = $this->entity->getEuid();
            $this->setUname($uname);
        }
        $this->entityEuid = $this->entity->getEuid();
        return $this;
    }

    /**
     * get uname
     * 
     * @return string
     */
    public function getUname(): string
    {
        return (string)$this->id;
    }

    /**
     * set uname
     * 
     * @param string $uname
     * @return static
     */
    public function setUname(string $uname): static
    {
        // dump($this);
        if($this->getSelfState()->isLoaded() && $this->id !== $uname) {
            // Can not update Uname if already set in database
            if($this->getEmbededStatus()->isDevOrSadmin()) {
                throw new Exception(vsprintf('Error %s line %d:%s- Cant not update Uname as %s: Uname is already set with value %s!', [__METHOD__, __LINE__, PHP_EOL, json_encode($uname), json_encode($this->id)]));
            }
        }
        if (!Encoders::isUnameFormatValid($uname)) throw new Exception(vsprintf('Error %s line %d:%s- Uname %s is invalid!', [__METHOD__, __LINE__, PHP_EOL, json_encode($uname)]));
        if(in_array(strtolower($uname), static::RESERVED_UNAMES)) {
            throw new Exception(vsprintf('Error %s line %d:%s- Uname %s is reserved!', [__METHOD__, __LINE__, PHP_EOL, json_encode($uname)]));
        }
        $this->id = $uname;
        return $this;
    }

    /**
     * get entityEuid
     * 
     * @return string
     */
    public function getEntityEuid(): ?string
    {
        return $this->entityEuid ?? null;
    }

    public function getEntity(): ?TraitUnamedInterface
    {
        if(!isset($this->entity)) {
            $entity = $this->getEmbededStatus()?->wireEntityManager->getEntityByEuid($this->entityEuid) ?? null;
            if($entity instanceof TraitUnamedInterface) {
                $this->entity = $entity;
            }
        }
        return $this->entity ?? null;
    }
}

templates/generate/entities.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}

{% block title %}{{ 'title_generic'|trans }}{% endblock %}

{% block container %}
    <div class="max-w-3xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">App Entities</h1>

        <div class="max-w-2xl mx-auto my-2 flex flex-col gap-2">
            {% if class is not null %}
            <h3>{{ class }} <a href="{{ path('app_entities') }}" title="Retour à la liste"><twig:ux:icon name="tabler:arrow-back-up" class="h-6 w-6 text-slate-600 inline-block" /></a></h3>
            <pre>
                {{ dump(entities) }}
            </pre>
            {% else %}
                <a{{ turbo_preload(false) }} href="{{ path('admin_user_index') }}"><twig:ux:icon name="tabler:eye" class="h-6 w-6 inline-block" /> Users</a>
                {% for class,shortname in classnames %}
                <a{{ turbo_preload(false) }} href="{{ path('app_entities', {class: shortname}) }}"><twig:ux:icon name="tabler:eye" class="h-6 w-6 inline-block" /> {{ class }}</a>
                {% endfor %}
            {% endif %}
        </div>

	</div>
{% endblock %}

templates/generate/generate.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}

{% block title %}{{ 'title_generic'|trans }}{% endblock %}

{% block container %}
    <div class="max-w-3xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">Generate entities</h1>
		{{ parent()}}

		<div class="max-w-2xl mx-auto my-2">
			<h3 class="text-center font-black">Choose your options</h3>
			<div>{{ form(form) }}</div>
		</div>

		<div{{ turbo_memory(false) }}>

			<div class="max-w-2xl mx-auto my-2">
				{% for name,opresult in hydrateds|default([]) %}
				<h3 class="text-center font-black">{{ name|capitalize }} {{ opresult.data|length }}</h3>
				{% if opresult.success %}
					{% for entity in opresult.data %}
					<div>
						<h4 class="text-center my-2">{{ entity.shortname }} {{ entity.name }}</h4>
						{{ dump(entity) }}
					</div>
					{% endfor %}
				{% else %}
					<code>{{ opresult.printMessages(true) }}</code>
					<div>{{ dump(opresult.data) }}</div>
				{% endif %}
				{% endfor %}
			</div>

		</div>

	</div>
{% endblock %}

templates/generate/orphanunames.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}
{% import "@AequationWire/partials/_elements.html.twig" as elements %}

{% block title %}
	{{ 'title_generic'|trans }}
{% endblock %}

{% block container %}
	<div class="max-w-7xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">Orphan Unames</h1>
		{{ parent()}}

        <div class="max-w-7xl mx-auto my-2">
            <h3 class="text-center font-black">Orphan Unames list</h3>
            <div class="flex flex-grow gap-1 justify-center items-center">
                <div class="text-center min-w-[120px] border border-slate-700 rounded px-6 py-2">
                    Found:
                    <span class="font-black">{{ unames|length }}</span><br>
                </div>
                {% if unames|length %}
                    <a{{turbo_preload(false)}} href="{{ path('app_orphanunames_cleanup') }}" class="px-6 py-2 min-w-[120px] text-center text-white bg-sky-600 border border-sky-600 rounded active:text-sky-500 hover:bg-transparent hover:text-sky-600 focus:outline-none focus:ring">Remove all orphans</a>
                {% endif %}
            </div>

            {% if results is defined %}
            {{ elements.opresult_messages(results) }}
            {% endif %}

            <div class="mt-3">
                <div class="block w-full overflow-x-auto border rounded-md border-slate-600">
                    <table class="items-center w-full bg-transparent border-collapse">
                        <thead>
                            <tr>
                                <th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-black text-left uppercase border-l-0 border-r-0 whitespace-nowrap">ID</th>
                                {# <th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">Uname EUID</th> #}
                                <th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">Entity EUID</th>
                                <th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-100">
                            {% for uname in unames %}
                                <tr class="text-slate-500">
                                    <th class="border-t-0 px-4 align-middle text-sm font-semibold text-sky-800 whitespace-nowrap p-4 text-left">
                                        {% if uname.entityEuid == uname.id %}
                                            {{ uname.id }}
                                        {% else %}
                                            <span class="font-bold text-sky-600">{{ uname.id }}</span>
                                        {% endif %}
                                    </th>
                                    {# <th class="border-t-0 px-4 align-middle p-4 text-center">{{ uname.euid }}</th> #}
                                    <th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-left">{{ uname.entityEuid }}</th>
                                    <th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">
                                        <div class="flex gap-2">
                                            <a{{turbo_preload(false)}} href="{{ path('app_orphanunames_cleanup', {'euid': uname.euid}) }}" class="inline px-6 py-2 min-w-[120px] text-center text-white bg-sky-600 border border-sky-600 rounded active:text-sky-500 hover:bg-transparent hover:text-sky-600 focus:outline-none focus:ring">Remove</a>
                                        </div>
                                    </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

	</div>

</div>{% endblock %}

templates/generate/report.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}

{% block title %}
	Admin generate {{ app.factory.name|default('Website data') }}
{% endblock %}

{% block main_content %}
	<div class="max-w-7xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">Generation report {{ app.factory.name|default('Website data') }}</h1>
		{# {{ parent()}} #}

		<div{{turbo_memory(false)}}>

			<div class="flex flex-row items-center">
				<div class="text-center my-2">
					{% for num,name in available_modes %}
					{% if num == mode %}
					<span class="rounded m-0 py-1 px-2 font-semibold bg-orange-800 text-orange-100">{{ name }}</span>
					{% else %}
					<a{{ turbo_preload(false) }} href="{{ path('generate_report', {mode: num}) }}" class="rounded m-0 py-1 px-2 font-semibold text-sky-600 hover:bg-sky-800 hover:text-sky-100">{{ name }}</a>
					{% endif %}
					{% endfor %}
				</div>
			</div>

			<div class="max-w-7xl mx-auto my-2">
				{% for classname,reports in class_reports %}
				<h3 class="font-black italic mb-0">Class: {{ classname }} <a{{ turbo_preload(false) }} href="{{ path('generate_report_entity', {entity: classname|shortname, mode: mode}) }}">
					<twig:ux:icon name="tabler:eye" class="h-6 w-6 text-slate-600 inline-block" />
				</a></h3>
				<div class="mt-2 mb-4">
					{{ toDump(reports, 3, ['identifier']) }}
				</div>
				{% endfor %}
			</div>

		</div>

	</div>

    <span class="hidden h-8 w-8 text-lime-600"></span>
    <span class="hidden h-8 w-8 text-red-600"></span>
    <span class="hidden bg-orange-800 text-orange-100"></span>
{% endblock %}

templates/generate/report_entity.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}

{% block title %}
	{{ 'title_generic'|trans }}
{% endblock %}

{% block container %}
	<div class="max-w-7xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">Generation report <span class="text-blue-900">{{ entity }}</span> <a{{ turbo_preload(false) }} href="{{ path('app_report', {mode: mode}) }}"><twig:ux:icon name="tabler:arrow-back-up" class="h-6 w-6 text-slate-600 inline-block" /></a></h1>
		{# {{ parent()}} #}

		<div{{turbo_memory(false)}}>

			<div class="flex flex-row items-center">
				<div class="text-center my-2">
					{% for num,name in available_modes %}
					{% if num == mode %}
					<span class="rounded m-0 py-1 px-2 font-semibold bg-orange-800 text-orange-100">{{ name }}</span>
					{% else %}
					<a{{ turbo_preload(false) }} href="{{ path('app_report_entity', {entity: entity, mode: num}) }}" class="rounded m-0 py-1 px-2 font-semibold text-sky-600 hover:bg-sky-800 hover:text-sky-100">{{ name }}</a>
					{% endif %}
					{% endfor %}
				</div>
			</div>

			{% if app.dev %}
				{% for classname,reports in class_reports %}
				<div class="max-w-7xl mx-auto my-2">
					<h3 class="font-black italic mb-0">Class: {{ classname }}</h3>
					{{ dump(reports) }}
				</div>
				{% endfor %}
				</pre>
			{% else %}
				<div class="max-w-7xl mx-auto my-2">
					<div class="border border-slate-600 rounded-md p-2 my-2">
						<h3 class="font-black italic mb-0">Current path:</h3>
						<div>{{ normalizer.currentPath }}</div>
					</div>

					{% for reports in class_reports %}
					<div class="block w-full overflow-x-auto border rounded-md border-slate-600">
						<table class="items-center w-full bg-transparent border-collapse">
							<thead>
								<tr>
									<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Order</th>
									<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Enabled</th>
									<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">File/Classname</th>
									<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">Dependencies</th>
									<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Items</th>
									{# <th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap min-w-140-px">Progress</th> #}
								</tr>
							</thead>
							<tbody class="divide-y divide-slate-100">
								{% for order,data in reports %}
								<tr class="text-slate-500">
									<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ order }}</th>
									<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ data.enabled and data.valid ? ux_icon('tabler:check', {class: 'inline-block h-8 w-8 text-lime-600'}) : ux_icon('tabler:x', {class: 'inline-block h-8 w-8 text-red-600'}) }}</th>
									<td class="border-t-0 px-4 align-middle text-xs font-medium text-slate-900 whitespace-nowrap p-4">{{ name }}<br>{{ data.entity }}</td>
									{% if data.dependencies.valid %}
									<td class="border-t-0 px-4 align-middle text-xs font-medium text-slate-900 whitespace-nowrap p-4"><ul><li>{{ data.dependencies.relations|keys|join('</li><li>')|raw }}</li></ul></td>
									{% else %}
									<td class="border-t-0 px-4 align-middle text-xs font-light italic text-slate-700 whitespace-nowrap p-4">INVALID ENTITY</td>
									{% endif %}
									<td class="border-t-0 px-4 align-middle text-xs font-medium text-slate-900 whitespace-nowrap p-4 text-center">{{ data.items|length }}</td>
									{# <td class="border-t-0 px-4 align-middle text-xs whitespace-nowrap p-4">
										{% set ratio = (4 + random(16)) * 5 %}
										<div class="flex items-center">
											<span class="mr-2 text-xs font-medium">{{ ratio }}%</span>
											<div class="relative w-full">
												<div class="w-full bg-sky-200 rounded-full h-4 border border-sky-500 overflow-hidden">
													<div class="bg-gradient-to-r from-sky-500 to-sky-600 h-4" style="width: {{ ratio }}%"></div>
												</div>
											</div>
										</div>
									</td> #}
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					{% endfor %}

				</div>
			{% endif %}

			<div class="max-w-7xl mx-auto my-2">
				{# {{ dump((class_reports|first).dependencies.relations) }} #}
			</div>

		</div>

	</div>

    <span class="hidden h-8 w-8 text-lime-600"></span>
    <span class="hidden h-8 w-8 text-red-600"></span>
    <span class="hidden bg-orange-800 text-orange-100"></span>
{% endblock %}

templates/generate/uow.html.twig
{% extends '@AequationWire/admin/base_admin.html.twig' %}

{% block title %}
	{{ 'title_generic'|trans }}
{% endblock %}

{% block container %}
	<div class="max-w-7xl px-4 mt-4 pb-24 mx-auto">
		<h1 class="text-3xl italic text-blue-700">UnitOfWork tests</h1>
		{{ parent()}}

		<div{{turbo_memory(false)}}>

			<div class="max-w-7xl mx-auto my-2">
				<h3 class="text-center font-black">UOW & Entities</h3>
				<div class="flex flex-grow gap-1 justify-center items-center">
					<div class="text-center border border-slate-700 rounded-lg p-2 mb-1">
						UnitOfWork size : <span class="font-black">{{ UnitOfWork.size() }}</span><br>
					</div>
					<div class="text-center border border-slate-700 rounded-lg p-2 mb-1">
						Has pending insertions: <span class="font-black">{{ UnitOfWork.hasPendingInsertions() ? 'true' : 'false' }}</span><br>
					</div>
				</div>
				{% for data in entities %}
				<div class="border border-slate-700 rounded-lg p-4 mb-2">
					<h4 class="text-center text-slate-900 font-black"><span class="text-slate-500">{{ data.entity.classname }}</span> is <span class="text-sky-600">{{ data.state|lower }}</span></h4>
					<div class="text-lg font-thin italic text-slate-800 text-center">{{ data.commentaire|raw }}</div>
					<div class="mt-3">
						{# {{ dump(data.entity) }} #}
						<div class="block w-full overflow-x-auto border rounded-md border-slate-600">
							<table class="items-center w-full bg-transparent border-collapse">
								<thead>
									<tr>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-black text-center uppercase border-l-0 border-r-0 whitespace-nowrap">ID</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">Name</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">State</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Contained</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Scheduled</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Insert</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Update</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">DirtyCheck</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">Delete</th>
										<th class="px-4 bg-slate-50 text-slate-700 align-middle py-3 text-xs font-semibold text-center uppercase border-l-0 border-r-0 whitespace-nowrap">EmbededStatus</th>
									</tr>
								</thead>
								<tbody class="divide-y divide-slate-100">
									<tr class="text-slate-500">
										<th class="border-t-0 px-4 align-middle p-4 text-center"><div class="rounded-full py-1 px-2 text-lg font-black whitespace-nowrap text-white bg-black">{{ data.entity.id|default('?') }}</div></th>
										<th class="border-t-0 px-4 align-middle text-sm font-bold text-sky-600 whitespace-nowrap p-4 text-left">{{ data.entity.name|default('???') }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ data.state }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ em.contains(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ UnitOfWork.isEntityScheduled(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ UnitOfWork.isScheduledForInsert(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ UnitOfWork.isScheduledForUpdate(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ UnitOfWork.isScheduledForDirtyCheck(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ UnitOfWork.isScheduledForDelete(data.entity) ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
										<th class="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-center">{{ data.entity.hasEmbededStatus() ? ux_icon('tabler:square-check-filled', {class: 'w-6 h-6 inline-block text-lime-500'}) : ux_icon('tabler:square-check', {class: 'w-6 h-6 inline-block text-slate-300'}) }}</th>
									</tr>
								</tbody>
							</table>
						</div>

					</div>
				</div>
				{% endfor %}
			</div>

			<div class="max-w-7xl mx-auto my-2">
				<h3 class="text-center font-black">UOW tests</h3>
				<div>{{ dump(UnitOfWork.identityMap) }}</div>
				{# <div>{{ dump(UnitOfWork.identityMap) }}</div> #}
				{# <div>{{ dump(UnitOfWork.identityMap) }}</div> #}
				{# <div>{{ dump(UnitOfWork.identityMap) }}</div> #}
			</div>

		</div>

	</div>
{% endblock %}